stages:
    - test
    - deploy
    - deploy-aws

test:
  image: python:3.7
  stage: test
  services:
    - postgres:10.9
  variables:
    DJANGO_SETTINGS_MODULE: "app.settings.test"
    DATABASE_URL: postgres://testuser:testpass@postgres/test_db
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpass
  script:
    - pip install -r requirements-dev.txt
    - black --check .
    - pytest src -p no:warnings

deploydevelop:
    image: ilyasemenov/gitlab-ci-git-push
    stage: deploy
    script: git-push dokku@bitwarden.bullet-train.io:bullet-train
    only:
        - develop

deployawsstaging:
    image: bullettrain/elasticbeanstalk-pipenv  # TODO: remove pipenv from this docker image
    stage: deploy-aws
    script:
        - export AWS_ACCESS_KEY_ID=$AWS_STAGING_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_STAGING_SECRET_ACCESS_KEY
        - export DATABASE_URL=$DATABASE_URL_STAGING
        - export GOOGLE_ANALYTICS_CLIENT_ID=$GOOGLE_ANALYTICS_CLIENT_ID_STAGING
        - export GOOGLE_ANALYTICS_KEY=$GOOGLE_ANALYTICS_KEY_STAGING
        - export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE_STAGING
        - cp requirements.txt ./src/requirements.txt
        - sh generate.sh
        - git config --global user.email "build@gitlab.com" 
        - git config --global user.name "Gitlab"
        - git add . && git commit -m "Commit to EB"
        - cd src
        - eb deploy $EB_ENVIRONMENT_STAGING
    only:
        - staging

deployawsmaster:
    image: bullettrain/elasticbeanstalk-pipenv
    stage: deploy-aws
    script:
        - export DATABASE_URL=$DATABASE_URL_PRODUCTION
        - export GOOGLE_ANALYTICS_CLIENT_ID=$GOOGLE_ANALYTICS_CLIENT_ID_PRODUCTION
        - export GOOGLE_ANALYTICS_KEY=$GOOGLE_ANALYTICS_KEY_PRODUCTION
        - export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE_PRODUCTION
        - cp requirements.txt ./src/requirements.txt
        - sh generate.sh
        - git config --global user.email "build@gitlab.com" 
        - git config --global user.name "Gitlab"
        - git add . && git commit -m "Commit to EB"
        - cd src
        - eb deploy $EB_ENVIRONMENT_PRODUCTION --timeout 30
    only:
        - master
        - master-aws