version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bullettrain
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "python manage.py migrate --noinput
              && python manage.py collectstatic --noinput
              && gunicorn --bind 0.0.0.0:8000 -w 3 app.wsgi"
    environment:
      DJANGO_DB_NAME: bullettrain
      DJANGO_DB_USER: postgres
      DJANGO_DB_PASSWORD: password
      DJANGO_DB_PORT: 5432
      DJANGO_ALLOWED_HOST: localhost
    ports:
     - "8000:8000"
    depends_on:
      - db
    links:
      - db:db