name: Frontend Audit

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Audit
        working-directory: frontend
        run: |
          npm i --legacy-peer-deps
          npm audit --audit-level high
